import type { Module } from "./data";

export const curriculumModules: Module[] = [
  {
    id: "os-jaringan",
    number: "09",
    title: "Instalasi Sistem Operasi Jaringan",
    icon: "terminal",
    duration: "45 menit",
    level: "Dasar",
    summary: "Mengenal perbedaan instalasi server GUI dan CLI, lalu mensimulasikan Debian Server lewat container.",
    objectives: ["Membedakan GUI dan CLI", "Memahami alur instalasi OS jaringan", "Mengenal package manager", "Mengecek identitas sistem"],
    theory: {
      title: "Apa itu Sistem Operasi Jaringan (Network Operating System)?",
      summary: "Sistem Operasi Jaringan (NOS) adalah sistem operasi yang dirancang khusus untuk mengelola sumber daya jaringan, melayani permintaan multi-user, dan menjalankan layanan server secara andal 24/7.",
      points: [
        { term: "Arsitektur Server vs Desktop", desc: "OS Desktop mengutamakan antarmuka grafis (GUI), kenyamanan multimedia, dan penggunaan single-user. OS Jaringan mengutamakan stabilitas, keamanan, efisiensi RAM/CPU, dan otomasi berbasis baris perintah (CLI)." },
        { term: "Kernel Linux & Hak Akses Root", desc: "Inti sistem operasi yang menjembatani hardware dan aplikasi server. Di Linux, akun `root` memiliki kekuasaan penuh, sementara akun pengguna biasa dibatasi untuk menjaga keamanan sistem." },
        { term: "Paket Repositori & APT", desc: "Kumpulan ribuan software resmi yang telah diuji kestabilannya. Perintah `apt update` memperbarui katalog daftar paket, dan `apt install` mengunduh serta memasang paket secara terverifikasi." },
      ],
    },
    steps: [
      { title: "Pahami GUI dan CLI", description: "Server nyata biasanya memakai mode CLI agar ringan. GUI lebih mudah dilihat, tetapi memakan RAM dan CPU lebih besar. Di lab Docker, siswa berlatih Debian CLI yang mirip server produksi.", commands: [{ label: "Perbandingan", where: "Host", command: "GUI = tampilan grafis, cocok untuk desktop\nCLI = terminal teks, cocok untuk server\nServer ASJ biasanya dikelola lewat CLI", explanation: "GUI (Graphical User Interface) → tampilan visual dengan jendela, ikon, dan mouse\nCLI (Command Line Interface) → hanya teks, semua diketik manual\nServer produksi umumnya CLI karena:\n  - Lebih hemat RAM (tidak perlu render grafis)\n  - Lebih cepat untuk otomasi via script\n  - Bisa diakses remote via SSH tanpa perlu tampilan" }] },
      { title: "Simulasi Debian Server", description: "Container Debian menggantikan instalasi manual untuk latihan perintah dasar. Ini membuat praktik cepat, aman, dan mudah diulang.", commands: [{ label: "Jalankan Debian latihan", where: "Host", command: "docker run -dit --name os-asj --hostname os-asj --network lab-asj --memory 256m debian:12-slim sleep infinity\ndocker exec -it os-asj bash", explanation: "docker run → membuat container Debian baru\n--name os-asj → nama container untuk latihan OS\n--hostname os-asj → nama host di dalam container\n--network lab-asj → terhubung ke jaringan lab\n--memory 256m → batas RAM 256 MB\ndebian:12-slim → image Debian 12 versi ringan\nsleep infinity → menjaga container tetap menyala\ndocker exec -it os-asj bash → masuk ke shell Debian" }] },
      { title: "Cek sistem dan repositori", description: "Siswa mengenali versi OS, user aktif, direktori kerja, dan cara memperbarui daftar paket.", commands: [{ label: "Perintah dasar", where: "Container", command: "cat /etc/os-release\nwhoami\npwd\nls /\napt update\nexit", explanation: "cat /etc/os-release → menampilkan info OS (nama, versi, ID Debian)\nwhoami → menampilkan user yang sedang aktif (biasanya root di container)\npwd → Print Working Directory: menampilkan direktori kerja saat ini\nls / → menampilkan isi direktori root (/, paling atas di Linux)\napt update → memperbarui daftar paket dari repositori Debian\nexit → keluar dari container kembali ke host" }] },
      { title: "Bandingkan dengan instalasi nyata", description: "Pada server nyata, tahapnya adalah boot ISO, partisi disk, pilih paket, atur user, jaringan, lalu login. Pada lab ini tahap tersebut diringkas karena Docker sudah menyediakan sistem dasarnya.", note: "Guru tetap bisa menjelaskan instalasi Debian Server nyata lewat demo atau video, lalu praktik layanan dilakukan di container." },
    ],
    test: [{ label: "Validasi", where: "Host", command: "docker exec os-asj cat /etc/debian_version\ndocker ps --filter name=os-asj", explanation: "docker exec os-asj cat /etc/debian_version → menampilkan versi Debian di dalam container\ndocker ps --filter name=os-asj → menampilkan status container os-asj (pastikan Up)" }],
  },
  {
    id: "remote",
    number: "10",
    title: "Remote Server SSH dan Telnet",
    icon: "terminal",
    duration: "45 menit",
    level: "Menengah",
    summary: "Mengaktifkan akses remote ke container Debian dan membandingkan SSH yang aman dengan Telnet yang tidak terenkripsi.",
    objectives: ["Menginstal OpenSSH Server", "Membuat user remote", "Menguji login SSH", "Memahami risiko Telnet"],
    warning: "Telnet hanya untuk demonstrasi konsep. Jangan gunakan Telnet untuk akun nyata karena username dan password tidak terenkripsi.",
    theory: {
      title: "Apa itu Remote Server, SSH (Port 22), & Bahaya Telnet (Port 23)?",
      summary: "Remote Server memungkinkan administrator jaringan mengelola dan mengetik perintah di komputer server dari jarak jauh melalui koneksi jaringan tanpa harus berada di depan layar fisik server.",
      points: [
        { term: "SSH (Secure Shell - Port 22)", desc: "Protokol remote standar industri modern. Seluruh lalu lintas data, keystroke, dan password dienkripsi secara end-to-end menggunakan kriptografi kunci publik dan simetris (AES)." },
        { term: "Telnet (Telecommunication Network - Port 23)", desc: "Protokol remote generasi lama yang mengirimkan seluruh karakter dalam bentuk teks polos (plain-text). Siapa pun yang melakukan packet sniffing di jaringan (Wireshark) dapat mencuri password server dengan mudah." },
        { term: "OpenSSH Server (sshd)", desc: "Aplikasi daemon SSH di Linux yang mendengarkan permintaan koneksi remote di port 22 dan mengotentikasi user." },
        { term: "Prinsip Non-Root Remote", desc: "Sangat disarankan menonaktifkan login langsung akun `root` lewat SSH (`PermitRootLogin no`) dan mewajibkan login menggunakan user biasa terlebih dahulu demi audit jejak digital." },
      ],
    },
    steps: [
      { title: "Buat remote server", description: "Container ini menjadi server yang akan diakses dari host dan client-asj.", commands: [{ label: "Container", where: "Host", command: "docker run -dit --name remote-asj --hostname remote.sekolah.test --network lab-asj --ip 172.25.0.22 -p 2222:22 --memory 384m debian:12-slim sleep infinity\ndocker exec -it remote-asj bash", explanation: "docker run → membuat container untuk remote server\n--name remote-asj → nama container\n--ip 172.25.0.22 → IP tetap remote server\n-p 2222:22 → port 2222 host diteruskan ke port 22 (SSH) di container\n--memory 384m → batas RAM 384 MB\ndocker exec → masuk ke container" }] },
      { title: "Instal SSH server", description: "OpenSSH dipakai untuk remote server secara aman. Buat user siswa agar tidak memakai root.", commands: [{ label: "Setup SSH", where: "Container", command: "apt update\napt install -y openssh-server sudo nano iproute2\nuseradd -m -s /bin/bash siswa\necho 'siswa:BelajarSSH2026!' | chpasswd\nmkdir -p /run/sshd\n/usr/sbin/sshd\nexit", explanation: "apt install openssh-server → menginstal server SSH (Secure Shell)\nsudo → agar user siswa bisa menjalankan perintah admin\nnano → editor teks\niproute2 → perintah ip untuk cek jaringan\nuseradd -m -s /bin/bash siswa → membuat user 'siswa' dengan home directory\necho '...' | chpasswd → mengatur password user siswa\nmkdir -p /run/sshd → membuat direktori yang dibutuhkan SSH daemon\n/usr/sbin/sshd → menjalankan SSH server\nexit → keluar dari container" }] },
      { title: "Uji login SSH", description: "Port 2222 di laptop host diteruskan ke port 22 di container. Dari container client, akses langsung ke IP lab.", commands: [{ label: "Dari host", where: "Host", command: "ssh siswa@localhost -p 2222", explanation: "ssh → perintah untuk remote login yang aman (terenkripsi)\nsiswa@localhost → login sebagai user 'siswa' ke komputer sendiri (localhost)\n-p 2222 → menggunakan port 2222 (karena port 22 di-mapping ke 2222)" }, { label: "Dari client", where: "Host", command: "docker exec -it client-asj ssh siswa@172.25.0.22", explanation: "docker exec -it client-asj → menjalankan perintah dari container client\nssh siswa@172.25.0.22 → login SSH ke IP remote server di jaringan lab\nPort default 22 dipakai langsung karena client dan server di jaringan yang sama" }] },
      { title: "Demonstrasi Telnet", description: "Telnet ditunjukkan agar siswa memahami mengapa protokol lama berbahaya untuk login server.", commands: [{ label: "Pasang client telnet", where: "Host", command: "docker exec client-asj apt install -y telnet", explanation: "Menginstal client telnet di container client-asj\nTelnet mengirim data TANPA enkripsi (termasuk password)\nSiapa saja di jaringan bisa menyadap login telnet\nGunakan SSH untuk remote yang aman, Telnet hanya untuk belajar perbandingan" }], note: "Untuk praktik utama, gunakan SSH. Telnet cukup dibahas sebagai perbandingan keamanan." },
    ],
    test: [{ label: "Cek port SSH", where: "Host", command: "docker exec client-asj nc -vz 172.25.0.22 22", explanation: "nc -vz → netcat: mengecek apakah port 22 (SSH) terbuka\n-v = verbose (tampilkan detail)\n-z = scan saja tanpa mengirim data\nJika muncul 'succeeded' berarti SSH server aktif" }],
  },
  {
    id: "proxy",
    number: "11",
    title: "Proxy Server Squid",
    icon: "shield",
    duration: "45 menit",
    level: "Menengah",
    summary: "Membangun proxy lokal untuk memahami caching, pembatasan akses, dan filtering sederhana.",
    objectives: ["Menginstal Squid", "Mengatur ACL jaringan lab", "Menguji akses lewat proxy", "Menerapkan blokir domain contoh"],
    theory: {
      title: "Apa itu Proxy Server & Squid?",
      summary: "Proxy Server (Port 3128) adalah server perantara yang berdiri di antara komputer klien dan internet untuk melakukan tiga fungsi utama: Caching (mempercepat akses), Filtering (penyaringan konten), dan Anonymity/Security (keamanan jaringan).",
      points: [
        { term: "Forward Proxy", desc: "Proxy yang bertindak mewakili klien internal untuk mengakses server luar. Sangat umum digunakan di laboratorium sekolah dan kantor untuk menghemat kuota dan memblokir situs terlarang." },
        { term: "Web Caching", desc: "Proxy menyimpan salinan halaman web atau gambar yang sering diakses. Saat klien lain membuka situs yang sama, konten disajikan dari cache lokal tanpa perlu mengunduh ulang dari internet." },
        { term: "ACL (Access Control List)", desc: "Daftar aturan kendali akses pada konfigurasi Squid (`/etc/squid/squid.conf`) untuk menentukan siapa yang boleh memakai proxy (`src`) dan situs apa saja yang diblokir (`dstdomain`)." },
        { term: "Access Log (`/var/log/squid/access.log`)", desc: "Catatan log terperinci dari setiap permintaan HTTP yang lewat: waktu, IP klien, URL tujuan, serta status apakah diizinkan (`TCP_HIT/TCP_MISS`) atau ditolak (`TCP_DENIED`)." },
      ],
    },
    steps: [
      { title: "Buat proxy server", description: "Squid berjalan pada port 3128 dan hanya dipakai di jaringan lab.", commands: [{ label: "Container", where: "Host", command: "docker run -dit --name proxy-asj --hostname proxy.sekolah.test --network lab-asj --ip 172.25.0.88 -p 3128:3128 --memory 384m debian:12-slim sleep infinity\ndocker exec -it proxy-asj bash", explanation: "docker run → membuat container proxy server\n--name proxy-asj → nama container\n--ip 172.25.0.88 → IP tetap proxy server\n-p 3128:3128 → port 3128 (port default Squid proxy)\n--memory 384m → batas RAM 384 MB\ndocker exec → masuk ke container" }] },
      { title: "Instal Squid", description: "Paket Squid menyediakan layanan proxy HTTP untuk latihan manajemen akses.", commands: [{ label: "Instal", where: "Container", command: "apt update\napt install -y squid nano\ncp /etc/squid/squid.conf /etc/squid/squid.conf.bak", explanation: "apt install squid → menginstal Squid Proxy Server\nnano → editor teks\ncp ... .bak → membuat backup konfigurasi asli sebelum diedit\nKebiasaan baik: selalu backup config sebelum mengubahnya" }] },
      { title: "Izinkan jaringan lab", description: "ACL menentukan siapa yang boleh memakai proxy. Pada lab ini hanya subnet Docker lab-asj yang diizinkan.", commands: [{ label: "Konfigurasi dasar", where: "Container", command: "cat > /etc/squid/squid.conf <<'EOF'\nhttp_port 3128\nacl lab_asj src 172.25.0.0/24\nacl blokir dstdomain .example.com\nhttp_access deny blokir\nhttp_access allow lab_asj\nhttp_access deny all\naccess_log /var/log/squid/access.log\nEOF\nsquid -k parse\nservice squid start\nexit", explanation: "http_port 3128 → Squid mendengarkan di port 3128\nacl lab_asj src 172.25.0.0/24 → ACL (Access Control List): mendefinisikan sumber = jaringan lab\nacl blokir dstdomain .example.com → ACL: mendefinisikan domain yang akan diblokir\nhttp_access deny blokir → menolak akses ke domain yang masuk daftar 'blokir'\nhttp_access allow lab_asj → mengizinkan akses dari jaringan lab\nhttp_access deny all → menolak semua akses lainnya (keamanan)\naccess_log → mencatat semua akses ke file log\nsquid -k parse → mengecek sintaks konfigurasi (jika error akan ditampilkan)\nservice squid start → menjalankan Squid proxy\nexit → keluar dari container" }] },
      { title: "Uji dari client", description: "Client mengakses web melalui proxy. Jika domain masuk daftar blokir, akses ditolak oleh Squid.", commands: [{ label: "Tes proxy", where: "Host", command: "docker exec client-asj curl -x http://172.25.0.88:3128 http://example.org -I\ndocker exec client-asj curl -x http://172.25.0.88:3128 http://example.com -I", explanation: "curl -x http://172.25.0.88:3128 → mengakses web MELALUI proxy server\n-I → hanya menampilkan header HTTP (bukan isi halaman)\nhttp://example.org → domain yang TIDAK diblokir (seharusnya berhasil, HTTP 200)\nhttp://example.com → domain yang DIBLOKIR (seharusnya ditolak, HTTP 403 Forbidden)\nDengan ini siswa melihat langsung efek ACL proxy" }] },
    ],
    test: [{ label: "Log proxy", where: "Host", command: "docker exec proxy-asj tail -n 20 /var/log/squid/access.log", explanation: "tail -n 20 → menampilkan 20 baris terakhir file log\naccess.log → catatan semua permintaan HTTP yang melewati proxy\nDi log akan terlihat: waktu, IP client, URL tujuan, status (DENIED atau ALLOWED)" }],
  },
  {
    id: "hosting-panel",
    number: "12",
    title: "Control Panel Hosting",
    icon: "web",
    duration: "40 menit",
    level: "Menengah",
    summary: "Mengenal konsep control panel hosting melalui simulasi layanan web, database, domain, dan backup.",
    objectives: ["Memahami fungsi cPanel/CyberPanel", "Menghubungkan web dan database", "Mengenal virtual host", "Membuat backup sederhana"],
    theory: {
      title: "Apa itu Control Panel Hosting (cPanel / CyberPanel)?",
      summary: "Control Panel Hosting adalah antarmuka grafis (GUI) berbasis web yang mengintegrasikan pengelolaan seluruh layanan server (Web Server, Database, DNS, FTP, Email, SSL, dan Backup) dalam satu dasbor terpadu.",
      points: [
        { term: "Komponen Inti Hosting", desc: "1. Web Server (Apache/Nginx/OpenLiteSpeed) untuk melayani website.\n2. Database Server (MariaDB/MySQL) untuk data dinamis.\n3. DNS Zone Manager untuk memetakan domain.\n4. FTP/SFTP Account untuk upload file website.\n5. Mail Server (Postfix/Dovecot) untuk email domain sendiri.\n6. Backup Manager untuk pencadangan rutin." },
        { term: "Virtual Hosting & Multi-Domain", desc: "Kemampuan satu server tunggal menyajikan banyak situs berbeda (`sekolah.test`, `alumni.sekolah.test`) dengan direktori `DocumentRoot` terpisah." },
        { term: "Backup & Disaster Recovery (`tar -czf`)", desc: "Prinsip paling penting dalam administrasi server: selalu membuat arsip cadangan terkompresi secara berkala sebelum melakukan upgrade atau perubahan sistem." },
      ],
    },
    steps: [
      { title: "Pahami peran control panel", description: "Control panel hosting adalah antarmuka untuk membuat website, database, domain, akun FTP, SSL, email, dan backup. Di lab Docker, siswa memahami komponennya melalui layanan yang sudah dibuat satu per satu.", commands: [{ label: "Komponen hosting", where: "Host", command: "Web server  = Apache/Nginx\nDatabase    = MariaDB/MySQL\nDNS         = domain dan record\nFTP/SFTP    = upload file\nMail server = email domain\nBackup      = salinan data", explanation: "Control panel hosting (cPanel, CyberPanel, Plesk) menyatukan semua ini dalam satu antarmuka:\nWeb server → melayani halaman website\nDatabase → menyimpan data dinamis (user, produk, dll)\nDNS → mengarahkan nama domain ke IP server\nFTP/SFTP → mengunggah file website dari komputer lokal\nMail server → mengelola email dengan domain sendiri\nBackup → menyimpan salinan data untuk pemulihan" }] },
      { title: "Simulasi virtual host", description: "Siswa melihat bahwa satu server web bisa melayani lebih dari satu nama domain lokal.", commands: [{ label: "Virtual host contoh", where: "Host", command: "docker exec -it web-asj bash\nmkdir -p /var/www/sekolah\necho '<h1>Hosting Sekolah</h1>' > /var/www/sekolah/index.html\nprintf '%s\\n' '<VirtualHost *:80>' 'ServerName hosting.sekolah.test' 'DocumentRoot /var/www/sekolah' '</VirtualHost>' > /etc/apache2/sites-available/hosting.conf\na2ensite hosting.conf\napachectl graceful\nexit", explanation: "docker exec -it web-asj bash → masuk ke container web server\nmkdir -p /var/www/sekolah → membuat direktori baru untuk website kedua\necho '...' > index.html → menulis halaman HTML untuk hosting.sekolah.test\nprintf → menulis konfigurasi VirtualHost:\n  <VirtualHost *:80> → menangani koneksi di port 80\n  ServerName hosting.sekolah.test → nama domain untuk virtual host ini\n  DocumentRoot /var/www/sekolah → direktori file website\na2ensite hosting.conf → mengaktifkan konfigurasi virtual host di Apache\napachectl graceful → memuat ulang Apache tanpa menghentikan layanan\nexit → keluar dari container" }] },
      { title: "Backup file website", description: "Backup sederhana dibuat dengan tar agar siswa memahami prinsip pencadangan sebelum memakai control panel sungguhan.", commands: [{ label: "Backup", where: "Host", command: "docker exec web-asj tar -czf /tmp/backup-web-asj.tar.gz /var/www/html /var/www/sekolah\ndocker cp web-asj:/tmp/backup-web-asj.tar.gz ./backup-web-asj.tar.gz\nls -lh backup-web-asj.tar.gz", explanation: "tar -czf → membuat arsip terkompresi:\n  -c = create (buat arsip baru)\n  -z = gzip (kompresi agar ukuran kecil)\n  -f = file (simpan ke file yang ditentukan)\n/tmp/backup-web-asj.tar.gz → nama file backup di dalam container\n/var/www/html /var/www/sekolah → direktori yang di-backup\ndocker cp → menyalin file dari container ke laptop host\nls -lh → menampilkan file dengan ukuran yang mudah dibaca (KB/MB)" }] },
      { title: "Hubungkan dengan EdgeOne", description: "Untuk website statis seperti materi ini, EdgeOne Pages berperan sebagai platform hosting. Siswa bisa membandingkan hosting modern berbasis Git dengan control panel tradisional.", note: "Bagian ini cocok untuk diskusi kelas: cPanel/CyberPanel mengelola server, sedangkan EdgeOne Pages/Vercel/Netlify mengelola deploy dari Git." },
    ],
    test: [{ label: "Cek backup", where: "Host", command: "ls -lh backup-web-asj.tar.gz", explanation: "ls -lh → menampilkan detail file backup:\n  -l = format panjang (permissions, ukuran, tanggal)\n  -h = ukuran dalam format manusia (KB, MB)\nPastikan file backup ada dan ukurannya masuk akal" }],
  },
  {
    id: "security-troubleshooting",
    number: "13",
    title: "Keamanan dan Troubleshooting Server",
    icon: "shield",
    duration: "50 menit",
    level: "Penting",
    summary: "Menganalisis masalah layanan, membaca log, mengecek port, dan menerapkan hardening dasar server.",
    objectives: ["Membaca log layanan", "Mengecek port aktif", "Menguji koneksi antar-container", "Menerapkan prinsip hardening dasar"],
    warning: "Perintah keamanan di modul ini untuk lingkungan lab. Jangan menutup port atau menghapus konfigurasi server produksi tanpa rencana rollback.",
    theory: {
      title: "Prinsip Keamanan Server (Hardening) & Troubleshooting Jaringan",
      summary: "Hardening adalah proses pengamanan sistem server dengan mengurangi celah serangan (attack surface), menutup port yang tidak perlu, dan menyiapkan prosedur diagnosis saat terjadi gangguan layanan.",
      points: [
        { term: "Metodologi Troubleshooting Berlapis", desc: "1. Layer Jaringan: Cek konektivitas fisik/IP (`ping`).\n2. Layer Transport: Cek port terbuka (`nc -vz` / `netstat`).\n3. Layer Aplikasi: Cek status service & file log (`docker logs`, `tail -f /var/log/...`)." },
        { term: "Principle of Least Privilege", desc: "Setiap aplikasi, user, dan proses hanya boleh diberi hak akses minimum yang diperlukan untuk menjalankan tugasnya. Jangan menjalankan web app sebagai root." },
        { term: "Port Scanning & Audit Keamanan", desc: "Memeriksa port yang terbuka secara berkala agar tidak ada service liar atau backdoor yang aktif tanpa izin." },
        { term: "Defense-in-Depth", desc: "Menerapkan keamanan berlapis: Firewall -> Enkripsi SSH -> Sandboxing Container -> Validasi Input -> Backup Terenkripsi." },
      ],
    },
    steps: [
      { title: "Cek status semua container", description: "Troubleshooting dimulai dari melihat container mana yang hidup, berhenti, atau restart terus-menerus.", commands: [{ label: "Status global", where: "Host", command: "docker ps -a\ndocker stats --no-stream", explanation: "docker ps -a → menampilkan SEMUA container beserta statusnya:\n  Up = berjalan normal\n  Exited = sudah berhenti\n  Restarting = restart berulang (kemungkinan error)\ndocker stats --no-stream → menampilkan penggunaan CPU, RAM, dan jaringan saat ini\n  --no-stream = tampilkan sekali saja (tidak terus-menerus)" }] },
      { title: "Baca log layanan", description: "Log memberi petunjuk kesalahan konfigurasi, port bentrok, password salah, atau service belum berjalan.", commands: [{ label: "Log container", where: "Host", command: "docker logs web-asj\ndocker logs db-asj\ndocker logs dns-asj", explanation: "docker logs NAMA → menampilkan output/log container\nPerhatikan pesan error seperti:\n  - 'Address already in use' = port sudah dipakai\n  - 'Access denied' = password atau permission salah\n  - 'No such file' = file konfigurasi hilang\nTips: tambahkan --tail 50 untuk hanya melihat 50 baris terakhir" }] },
      { title: "Cek port dan koneksi", description: "Gunakan nc, curl, dig, dan ping untuk membedakan masalah jaringan, DNS, dan aplikasi.", commands: [{ label: "Tes koneksi", where: "Host", command: "docker exec client-asj ping -c 2 172.25.0.80\ndocker exec client-asj nc -vz 172.25.0.80 80\ndocker exec client-asj dig @172.25.0.53 web.sekolah.test +short\ndocker exec client-asj curl http://172.25.0.80", explanation: "ping -c 2 → mengirim 2 paket ICMP, mengecek apakah host bisa dijangkau\n  Jika gagal = masalah jaringan dasar\nnc -vz 172.25.0.80 80 → mengecek apakah port 80 terbuka\n  Jika gagal = Apache belum berjalan\ndig @172.25.0.53 web.sekolah.test → mengecek apakah DNS bisa me-resolve nama\n  Jika gagal = BIND belum aktif atau zona salah\ncurl http://172.25.0.80 → mengakses web server\n  Jika gagal = masalah aplikasi web" }] },
      { title: "Hardening dasar", description: "Siswa mengenal praktik dasar: password kuat, user non-root, update paket, batasi layanan yang terbuka, dan backup sebelum perubahan besar.", commands: [{ label: "Checklist hardening", where: "Host", command: "1. Gunakan password kuat dan unik\n2. Jangan login root untuk pekerjaan harian\n3. Jalankan apt update sebelum instal paket\n4. Buka hanya port yang dibutuhkan\n5. Backup konfigurasi sebelum diedit\n6. Baca log sebelum menghapus container", explanation: "Hardening = memperkuat keamanan server:\n1. Password kuat → minimal 12 karakter, kombinasi huruf, angka, simbol\n2. Non-root → root punya akses penuh, kesalahan bisa fatal. Gunakan sudo\n3. apt update → memastikan paket terbaru (termasuk patch keamanan)\n4. Port minimal → setiap port terbuka = pintu potensial serangan\n5. Backup config → bisa rollback jika konfigurasi baru bermasalah\n6. Baca log → memahami masalah sebelum mengambil tindakan berisiko" }] },
    ],
    test: [{ label: "Diagnosis cepat", where: "Host", command: "docker ps -a\ndocker network inspect lab-asj\ndocker system df", explanation: "docker ps -a → melihat status semua container\ndocker network inspect lab-asj → melihat detail jaringan dan IP container\ndocker system df → melihat penggunaan disk total Docker" }],
  },
];
